aconfig/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('JAYBLA-admin/', admin.site.urls),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
    path('users/',include('users.urls',namespace='users')),    
    path('',include('main.urls',namespace='main'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .views import *


app_name = 'dashboard'

urlpatterns = [    
    path('',dashboard, name='home'),

    #Jobs
    path('career/new/', create_job, name='create_job'),
    path('careers/', job_list, name='jobs'),
    path('careers/<int:job_id>/update/', update_job, name='update-job'),
    path('careers/<int:job_id>/', job_detail, name='job-detail'),
    path('careers/<int:job_id>/delete/', job_delete, name='delete-job'),

    #Projects
    path('projects/', projectlist,name='projectlist'),
    path('projects/new/', create_project, name='create_project'),
    path('projects/<int:project_id>/', project_detail, name='project-detail'),
    path('projects/<int:p_id>/update/', update_project, name='update-project'),
    path('projects/<int:p_id>/delete/', project_delete, name='delete-project'),

    #Project_Images
    path('project-images/', images,name='images'),
    path('project-images/new/', project_images, name='add_images'),    
    path('project-images/<int:image_id>/delete/', project_photo_delete, name='delete-project-image'),
    
        #Agroforests
    path('agroforests/', agroforestlist,name='agroforestlist'),
    path('agroforests/new/', create_agroforest, name='create_agroforest'),
    path('agroforests/<int:project_id>/', agroforest_detail, name='agroforest-detail'),
    path('agroforests/<int:p_id>/update/', update_agroforest, name='update-agroforest'),
    path('agroforests/<int:p_id>/delete/', agroforest_delete, name='delete-agroforest'),     
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home,name='site-home'),
    path('contact/', views.contact,name='contact'),
    path('ajax-contact/', views.process_contact, name='contact_post'),
    path('ajax-partiner/', views.process_partiner, name='partiner_post'),
    path('ajax-expert/', views.process_expert, name='expert_post'),
    path('ajax-market/', views.process_market, name='market_post'),
    path('ajax-donation/', views.process_donation, name='donation_post'),
    path('history/', views.history,name='history'),
    path('careers/', views.careers,name='careers'), 
    path('careers/announced-jobs', views.jobs,name='jobs'), 
    path('volunteer/', views.volunteer,name='volunteer'), 
    path('approach/', views.approach,name='approach'), 
    path('donate/', views.donate,name='donate'),
    path('expert-panelist/', views.expert_panelist,name='expert_panelist'),    
    path('get-connected-to-market/', views.get_connected_to_market,name='get_connected_to_market'),    
    path('get-expert/', views.get_expert,name='get_expert'),    
    path('resources/', views.resources,name='resources'),    
    path('statistics/', views.statistics,name='statistics'),        
    path('stories-of-hope/', views.stories,name='stories'),    
    path('team/', views.team,name='team'),
    path('testimonials/', views.testimonials,name='testimonials'),  
    path('trainings/', views.trainings,name='trainings'),  
    path('vision-mission/', views.vision_mission,name='vision_mission'),
    path('consultation/', views.consultation,name='consultation'),
    path('projects/', views.projects,name='projects'),    
]

dashboard/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Job(models.Model):
    title = models.CharField(max_length=200)
    responsibilities = RichTextField(blank=False)
    skills = RichTextField(blank=False)
    qualifications = RichTextField(blank=False)
    status = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name

    def active(self):
        return self.status == 'Active'
        
    def expired(self):
        return self.status == 'Expired'

class Project(models.Model):
    name = models.CharField(max_length=200)    
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name

class MultipleImage(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    images = models.FileField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
class Agroforest(models.Model):
    name = models.CharField(max_length=200)
    trees = models.IntegerField()
    people = models.IntegerField()
    acres = models.DecimalField(max_digits=12, decimal_places=3)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    

dashboard/forms.py
from django import forms
from .models import *
from bootstrap_modal_forms.forms import BSModalModelForm


class JobForm(forms.ModelForm):

    class Meta:
        model = Job
        fields = ['title', 'responsibilities', 'skills','qualifications',]

class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ['name',]

class ProjectPhotosForm(forms.ModelForm):

    class Meta:
        model = MultipleImage
        fields = ['images']

class AgroforestForm(forms.ModelForm):
    class Meta:
        model = Agroforest
        fields= ['name', 'trees', 'acres', 'people']

dashboard/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from .forms import *
from .models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin, UserPassesTestMixin
)
from bootstrap_modal_forms.generic import (
  BSModalDeleteView,
  BSModalUpdateView
)

@login_required(login_url='users:login')
def dashboard(request):
    template_name = 'dash-home.html'
    projects = Project.objects.all()
    active_adverts = Job.objects.filter(status='active')
    expired_adverts = Job.objects.filter(status='expired')
    context = {
        'active_adverts':active_adverts,
        'expired_adverts':expired_adverts,
        'projects':projects,
    }

    return render(request, template_name,context)

@login_required(login_url='users:login')
def portfolio_create(request):
    template_name = 'dashboard/create_portfolio.html'
    if request.POST:
        formSet = PortfolioFormSet(request.POST, request.FILES, prefix='portfolio')
        if formSet.is_valid():
            formSet.save()
            messages.success(request,'Uploaded successfully', extra_tags='alert alert-success')            
        else:
            messages.error(request, 'An error occured', extra_tags='alert alert-danger')
    else:
        formSet = PortfolioFormSet(prefix='portfolio')
    context = {'formset':formSet}
    return render(request,template_name,context)

@login_required(login_url='users:login')
def create_job(request):
    template_name = 'jobs/create.html'
    if request.POST:
        form = JobForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Submitted Successfully', extra_tags='alert alert-success')
            return redirect(to='dashboard:jobs')
        else:
            messages.error(request, 'An error occured', extra_tags='alert alert-danger')
    else:
        form = JobForm()
    context = {'form':form}
    return render(request,template_name,context)


@login_required(login_url='users:login')
def job_list(request):
    template_name = 'jobs/list.html'
    jobs = Job.objects.all().order_by('-created_at')
    context = {'jobs':jobs}
    return render(request, template_name, context)


@login_required(login_url='users:login')
def update_job(request, job_id):
    template = 'jobs/update.html'
    job = get_object_or_404(Job, pk=job_id)

    job.title = request.POST['title']
    job.qualifications = request.POST['qualifications']
    job.skills = request.POST['skills']
    job.responsibilities = request.POST['responsibilities']
    job.status = request.POST['status']

    job.save()
    return redirect(to="dashboard:jobs")

@login_required(login_url='users:login')
def job_detail(request,job_id):
    template = 'jobs/detail.html'    
    job = get_object_or_404(Job, pk =job_id)   
    context = {
        'job' :job,      
    }    
    return render(request, template,context)

@login_required(login_url='users:login')
def job_delete(request,job_id):     
    job = get_object_or_404(Job, pk =job_id)   
    job.delete()
    return redirect(to="dashboard:jobs")


@login_required(login_url='users:login')
def project(request):
    if request.method == "POST":
        images = request.FILES.getlist('images')
        for image in images:
            Project.objects.create(images=image)
    images = Project.objects.all()
    return render(request, 'index.html', {'images': images})



@login_required(login_url='users:login')
def create_project(request):
    template_name = 'project/create.html'
    if request.POST:
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Submitted Successfully', extra_tags='alert alert-success')
            return redirect(to='dashboard:projectlist')
        else:
            messages.error(request, 'An error occured', extra_tags='alert alert-danger')
    else:
        form = ProjectForm()
    context = {'form':form}
    return render(request,template_name,context)

@login_required(login_url='users:login')
def projectlist(request):
    projects = Project.objects.all().order_by('-created_at')
    template_name = 'project/list.html' 
    context = {
        'projects':projects,
    }
    return render(request,template_name,context)

@login_required(login_url='users:login')
def project_detail(request,project_id):
    template = 'project/detail.html'    
    project = get_object_or_404(Project, pk =project_id)   
    context = {
        'project' :project,      
    }    
    return render(request, template,context)

@login_required(login_url='users:login')
def update_project(request, p_id):
    template = 'jobs/update.html'
    project = get_object_or_404(Project, pk=p_id)

    project.name = request.POST['name']
    project.save()
    return redirect(to="dashboard:projectlist")

@login_required(login_url='users:login')
def project_delete(request,p_id):     
    project = get_object_or_404(Project, pk =p_id)   
    project.delete()
    return redirect(to="dashboard:projectlist")


@login_required(login_url='users:login')
def project_images(request):
    template = 'project_images/create.html'
   
    if request.method=='POST':
        p_id = request.POST['project_id']        
        images = request.FILES.getlist('images')     
                
        if p_id=='None':
            projects = Project.objects.order_by('name')
            context = {
                'projects' : projects,
                'error_message' : 'Please select a Project',
            }
            return render(request, template, context)
        else:
            project = get_object_or_404(Project, pk=p_id)
            for image in images:
                MultipleImage.objects.create(images=image,project=project)

            image_list = MultipleImage.objects.all()
            context = {
            'images' : image_list,		
            }
        return render(request, template, context) 
    else:
        projects = Project.objects.all()
        image_list = MultipleImage.objects.all()        
        context = {			
            'images' : image_list,
            'projects':projects,			
        }
        return render(request, template, context)


@login_required(login_url='users:login')
def images(request):
    template = 'project_images/list.html'
    image_list = MultipleImage.objects.all()        
    context = {			
        'images' : image_list,       		
    }
    return render(request, template, context)

@login_required(login_url='users:login')
def project_photo_delete(request,image_id):     
    image = get_object_or_404(MultipleImage, pk =image_id)   
    image.delete()
    return redirect(to="dashboard:images")


# AGROFOREST PROJECT
@login_required(login_url='users:login')
def create_agroforest(request):
    template_name = 'agroforest/create.html'
    if request.POST:
        form = AgroforestForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Submitted Successfully', extra_tags='alert alert-success')
            return redirect(to='dashboard:agroforestlist')
        else:
            messages.error(request, 'An error occured', extra_tags='alert alert-danger')
    else:
        form = AgroforestForm()
    context = {'form':form}
    return render(request,template_name,context)

@login_required(login_url='users:login')
def agroforestlist(request):
    agroforests = Agroforest.objects.all().order_by('-created_at')
    template_name = 'agroforest/list.html' 
    context = {
        'agroforests':agroforests,
    }
    return render(request,template_name,context)

@login_required(login_url='users:login')
def agroforest_detail(request,project_id):
    template = 'agroforest/detail.html'    
    agroforest = get_object_or_404(Agroforest, pk =project_id)   
    context = {
        'project' :agroforest,      
    }    
    return render(request, template,context)

@login_required(login_url='users:login')
def update_agroforest(request, p_id):    
    project = get_object_or_404(Agroforest, pk=p_id)

    project.name = request.POST['name']
    project.trees = request.POST['trees']
    project.acres = request.POST['acres']
    project.people = request.POST['people']
    project.save()
    return redirect(to="dashboard:agroforestlist")

@login_required(login_url='users:login')
def agroforest_delete(request,p_id):     
    project = get_object_or_404(Agroforest, pk =p_id)   
    project.delete()
    return redirect(to="dashboard:agroforestlist")

dashboard/templates/agroforest/create.html
{% extends 'main_dashboard.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <form action="." method="post" novalidate>
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                <div class="card-body">
                    <div class="form-group">
                        <label>Name Of The Agroforest Project</label>
                        {% render_field form.name class="form-control" %}
                    </div>
                    <div class="form-group">
                        <label>Total Trees Planted</label>
                        {% render_field form.trees class="form-control" %}
                    </div>
                    <div class="form-group">
                        <label>Total Area Restored</label>
                        {% render_field form.acres class="form-control" %}
                    </div>
                    <div class="form-group">
                        <label>Total People Benefited</label>
                        {% render_field form.people class="form-control" %}
                    </div>
                    <button type="submit" class="btn btn-primary btn-lg ml-3 mb-3"><i class="fa fa-check-square-o"></i> Add</button>                  
                </div> 
                    
            </form>
        </div>
    </div>
</div>
{% endblock content %}
    

dashboard/templates/agroforest/detail.html
{% extends 'main_dashboard.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <form action="{% url 'dashboard:update-agroforest' project.id %}" method="post" novalidate>
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                <div class="card-body">
                    <div class="form-group">
                        <label>Name Of Agroforest project</label>
                        <input type="text" class="form-control" name="name" value="{{project.name}}">
                    </div>
                    <div class="form-group">
                        <label>Trees Planted</label>
                        <input type="text" class="form-control" name="trees" value="{{project.trees}}">
                    </div>
                    <div class="form-group">
                        <label>Acres Restored</label>
                        <input type="text" class="form-control" name="acres" value="{{project.acres}}">
                    </div>
                    <div class="form-group">
                        <label>People Benefited</label>
                        <input type="text" class="form-control" name="people" value="{{project.people}}">
                    </div>                   
                </div> 
                    <button type="submit" class="btn btn-primary btn-lg ml-3 mb-3"><i class="fa fa-check-square-o"></i> Update</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}
    

dashboard/templates/agroforest/list.html
{% extends 'main_dashboard.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-md-10 offset-md-1">
        <div class="card">
            <div class="card-header">
              <h3 class="card-title"><strong>Agroforest Projects</strong></h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="jobs-list" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>SN</th>                    
                    <th>Agroforest Project Name</th>
                    <th>Trees Planted</th>
                    <th>Acres Restored</th>
                    <th>People</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                    {% for p in agroforests %}
                    <tr>
                      <td>{{forloop.counter}}</td>
                      <td>{{p.name}}</td>
                      <td>{{p.trees}}</td>
                      <td>{{p.acres}}</td>
                      <td>{{p.people}}</td>
                      <td>
                        <a href="{% url 'dashboard:agroforest-detail' p.id %}" style="cursor:pointer;font-size: 22px">
                          <i class="fa fa-edit text-warning"> Edit</i>
                        </a><br>
                        <a href="{% url 'dashboard:delete-agroforest' p.id %}" style="cursor:pointer;font-size: 22px">
                          <i class="fa fa-trash text-danger">Delete</i>
                        </a>
                      </td>
                    </tr>
                   {% endfor %}
                </tbody>
              </table>
            </div>            
          </div>          
    </div>
</div>
{% endblock content %}


{% block javascript %}
    <script>
        $(document).ready(function () {
            $('#jobs-list').DataTable();
        });
    </script>
{% endblock javascript %}
    
    