aconfig/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('JAYBLA-admin/', admin.site.urls),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
    path('users/',include('users.urls',namespace='users')),    
    path('',include('main.urls',namespace='main'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .views import *


app_name = 'dashboard'

urlpatterns = [    
    path('',dashboard, name='home'),

    #Jobs
    path('career/new/', create_job, name='create_job'),
    path('careers/', job_list, name='jobs'),
    path('careers/<int:job_id>/update/', update_job, name='update-job'),
    path('careers/<int:job_id>/', job_detail, name='job-detail'),
    path('careers/<int:job_id>/delete/', job_delete, name='delete-job'),

    #Projects
    path('projects/', projectlist,name='projectlist'),
    path('projects/new/', create_project, name='create_project'),
    path('projects/<int:project_id>/', project_detail, name='project-detail'),
    path('projects/<int:p_id>/update/', update_project, name='update-project'),
    path('projects/<int:p_id>/delete/', project_delete, name='delete-project'),

    #Project_Images
    path('project-images/', images,name='images'),
    path('project-images/new/', project_images, name='add_images'),    
    path('project-images/<int:image_id>/delete/', project_photo_delete, name='delete-project-image'),
    
        #Agroforests
    path('agroforests/', agroforestlist,name='agroforestlist'),
    path('agroforests/new/', create_agroforest, name='create_agroforest'),
    path('agroforests/<int:project_id>/', agroforest_detail, name='agroforest-detail'),
    path('agroforests/<int:p_id>/update/', update_agroforest, name='update-agroforest'),
    path('agroforests/<int:p_id>/delete/', agroforest_delete, name='delete-agroforest'),     
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home,name='site-home'),
    path('contact/', views.contact,name='contact'),
    path('ajax-contact/', views.process_contact, name='contact_post'),
    path('ajax-partiner/', views.process_partiner, name='partiner_post'),
    path('ajax-expert/', views.process_expert, name='expert_post'),
    path('ajax-market/', views.process_market, name='market_post'),
    path('ajax-donation/', views.process_donation, name='donation_post'),
    path('history/', views.history,name='history'),
    path('careers/', views.careers,name='careers'), 
    path('careers/announced-jobs', views.jobs,name='jobs'), 
    path('volunteer/', views.volunteer,name='volunteer'), 
    path('approach/', views.approach,name='approach'), 
    path('donate/', views.donate,name='donate'),
    path('expert-panelist/', views.expert_panelist,name='expert_panelist'),    
    path('get-connected-to-market/', views.get_connected_to_market,name='get_connected_to_market'),    
    path('get-expert/', views.get_expert,name='get_expert'),    
    path('resources/', views.resources,name='resources'),    
    path('statistics/', views.statistics,name='statistics'),        
    path('stories-of-hope/', views.stories,name='stories'),    
    path('team/', views.team,name='team'),
    path('testimonials/', views.testimonials,name='testimonials'),  
    path('trainings/', views.trainings,name='trainings'),  
    path('vision-mission/', views.vision_mission,name='vision_mission'),
    path('consultation/', views.consultation,name='consultation'),
    path('projects/', views.projects,name='projects'),    
]

main/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=13)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
class Expert(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=13)
    village = models.CharField(max_length=200)
    district = models.CharField(max_length=200)
    region = models.CharField(max_length=200)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
class Market(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=13)
    village = models.CharField(max_length=200)
    district = models.CharField(max_length=200)
    region = models.CharField(max_length=200)
    crop = models.TextField()
    crop_qty = models.TextField()
    sell_time = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
class Donate(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    amount = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name

class Partiner(models.Model):
    name = models.CharField(max_length=200)
    organization = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    

main/forms.py
from django import forms
from .models import *


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields= ['name', 'phone', 'email', 'subject', 'message']


class ExpertForm(forms.ModelForm):
    class Meta:
        model = Expert
        fields= '__all__'
        
class MarketForm(forms.ModelForm):
    class Meta:
        model = Market
        fields= '__all__'
        
class DonateForm(forms.ModelForm):
    class Meta:
        model = Donate
        fields= '__all__'

class PartinerForm(forms.ModelForm):
    class Meta:
        model = Partiner
        fields= ['name', 'organization', 'address', 'city','country', 'message']
        

main/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.http import JsonResponse
from .forms import *
from .models import *
from dashboard.models import *

from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags


# Create your views here.
def home(request):
    template_name = 'home.html'
    form = ContactForm()
    partiner_form = PartinerForm()
    agroforest = Agroforest.objects.all()
    context = {
        'form':form,
        'partiner_form':partiner_form,
        'agroforest':agroforest,
        }
    return render(request,template_name,context)

def history(request):
    template_name = 'history.html'
    title="History"
    context = {
        "title":title,
    }
    return render(request,template_name,context)

def approach(request):
    template_name = 'approach.html'
    title="Our Approach"
    context = {
        "title":title,
    }
    return render(request,template_name,context)

def donate(request):
    template_name = 'donate.html'
    title="Donate"
    form = DonateForm
    context = {
        "title":title,
        "form":form,
    }
    return render(request,template_name,context)

def careers(request):
    template_name = 'careers.html'
    title="Careers"
    context = {
        "title":title,
    }
    return render(request,template_name,context)

def jobs(request):
    template_name = 'jobs.html'
    title="Announced Jobs"
    jobs =Job.objects.all().order_by('-created_at')
    context = {
        "title":title,
        "jobs":jobs,
    }
    return render(request,template_name,context)

def expert_panelist(request):
    template_name = 'expert_panelist.html'
    title="Expert Panelist"
    context = {
        "title":title,
    }
    return render(request,template_name,context)

def get_connected_to_market(request):
    template_name = 'get_connected_to_market.html'
    title="Get Connected To The Market"
    form = MarketForm
    context = {
        "title":title,
        "form":form,
    }
    return render(request,template_name,context)

def get_expert(request):
    template_name = 'get_expert.html'
    title="Get In Touch With An Expert"
    form = ExpertForm
    context = {
        "title":title,
        "form":form,
    }
    return render(request,template_name,context)

def resources(request):
    template_name = 'resources.html'
    title="Resources"
    context = {
        "title":title,
    }
    return render(request,template_name,context)

def statistics(request):
    template_name = 'statistics.html'
    title="Statistics"
    context = {
        "title":title,
    }
    return render(request,template_name,context)

def stories(request):
    template_name = 'stories.html'
    title="Stories Of Hope"
    context = {
        "title":title,
    }
    return render(request,template_name,context)

def projects(request):
    projects = Project.objects.all()
    template_name = 'projects.html'
    title="Our Projects"
    context = {
        "title":title,
        'projects':projects,
    }
    return render(request,template_name,context)

def team(request):
    template_name = 'team.html'
    title="The Team"
    context = {
        "title":title,
    }
    return render(request,template_name,context)

def testimonials(request):
    template_name = 'testimonials.html'
    title="Testimonials"
    context = {
        "title":title,
    }
    return render(request,template_name,context)

def trainings(request):
    template_name = 'trainings.html'
    title="Trainings"
    context = {
        "title":title,
    }
    return render(request,template_name,context)

def vision_mission(request):
    template_name = 'vision_mission.html'
    title="Vision & Mission"
    context = {
        "title":title,
    }
    return render(request,template_name,context)

def volunteer(request):
    template_name = 'volunteer.html'
    title="Volunteer with Us"
    context = {
        "title":title,
    }
    return render(request,template_name,context)

def consultation(request):
    template_name = 'consultation.html'
    title="Consultation"
    context = {
        "title":title,
    }
    return render(request,template_name,context)

def contact(request):
    template_name = 'contact.html'
    form = ContactForm()
    title="Contact Us"
    context = {
        'form':form,
         "title":title,
    }
    return render(request,template_name,context)

def process_contact(request):
    if request.is_ajax():
        if request.method == 'POST':
            name = request.POST['name'],
            phone = request.POST['phone'],            
            email = request.POST['email'],
            subject = request.POST['subject'],
            message = request.POST['message']
            
            contact = Contact(
                name=name,               
                phone=phone,
                email=email,
                subject=subject,                
                message=message
                
            )
            contact.save()
            subject = 'Agriwezesha Website Contact Form'
            html_message = render_to_string('mail_template.html', {
                'name':name, 
                'phone':phone,       
                'email': email,
                'message': message,
                'subject':subject, 
            })
            plain_message = strip_tags(html_message)
            recipient_list = ['agriwezesha@gmail.com',]
            from_email = "contact@agriwezesha.co.tz"
            mail.send_mail(subject,plain_message, from_email, recipient_list, html_message=html_message,fail_silently=False,)

            return JsonResponse({'msg': 'success'}, safe=False)
        else:
            return JsonResponse({'msg': 'error'})
        
def process_expert(request):
    if request.is_ajax():
        if request.method == 'POST':
            name = request.POST['name'],
            phone = request.POST['phone'],            
            village = request.POST['village'],
            district = request.POST['district'],
            region = request.POST['region'],
            message = request.POST['message']
            
            expert = Expert(
                name=name,               
                phone=phone,
                village=village,
                district=district,   
                region=region,                        
                message=message                
            )
            expert.save()
            subject = 'Need an Expert!'
            html_message = render_to_string('expert_mail_template.html', {
                'name':name, 
                'phone':phone,       
                'village': village,
                'district': district,
                'region':region,
                'message':message,
                'subject':subject,
            })
            plain_message = strip_tags(html_message)
            recipient_list = ['agriwezesha@gmail.com',]
            from_email = "contact@agriwezesha.co.tz"
            mail.send_mail(subject,plain_message, from_email, recipient_list, html_message=html_message,fail_silently=False,)

            return JsonResponse({'msg': 'success'}, safe=False)
        else:
            return JsonResponse({'msg': 'error'})
        
def process_market(request):
    if request.is_ajax():
        if request.method == 'POST':
            name = request.POST['name'],
            phone = request.POST['phone'],            
            village = request.POST['village'],
            district = request.POST['district'],
            region = request.POST['region'],
            crop = request.POST['crop']
            crop_qty = request.POST['crop_qty']
            sell_time = request.POST['sell_time']
            
            market = Market(
                name=name,               
                phone=phone,
                village=village,
                district=district,   
                region=region,                        
                crop = crop,
                crop_qty = crop_qty,
                sell_time = sell_time,         
            )
            market.save()
            subject = 'Get Connected to Market'
            html_message = render_to_string('market_mail_template.html', {
                'name':name, 
                'phone':phone,       
                'village': village,
                'district': district,
                'region':region,
                'crop' : crop,
                'crop_qty' :crop_qty,
                'sell_time' : sell_time,
                'subject':subject,
            })
            plain_message = strip_tags(html_message)
            recipient_list = ['agriwezesha@gmail.com',]
            from_email = "contact@agriwezesha.co.tz"
            mail.send_mail(subject,plain_message, from_email, recipient_list, html_message=html_message,fail_silently=False,)

            return JsonResponse({'msg': 'success'}, safe=False)
        else:
            return JsonResponse({'msg': 'error'})
        
        
def process_donation(request):
    if request.is_ajax():
        if request.method == 'POST':
            name = request.POST['name'],
            email = request.POST['email'],            
            amount = request.POST['amount'],
            
            donation = Donate(
                name=name,               
                email=email,
                amount=amount,        
            )
            donation.save()
            subject = 'Donation Information'
            html_message = render_to_string('donation_mail_template.html', {
                'name':name, 
                'email':email,       
                'amount': amount,
                'subject':subject,
            })
            plain_message = strip_tags(html_message)
            recipient_list = ['agriwezesha@gmail.com',]
            from_email = "contact@agriwezesha.co.tz"

main/templates/includes/desktop_header.html
{% load static %}
<div class="main-header md-hidden sm-hidden bg-light">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 pl-5 pr-5">
                <div class="col-wrap-table">
                    <div id="site-logo" class="site-logo col-media-left col-media-middle">
                        <a href="/"><img src="{% static 'images/logo.svg' %}" alt="Logo" style="height:100px;width:auto;"></a>
                    </div>
                    <div class="header-mainnav col-media-body col-media-middle">
                        <div id="site-navigation" class="main-navigation fright">
                            <ul id="primary-menu" class="menu">
                                <li class="menu-item">
                                    <a href="/">HOME</a>    
                                </li>
                                <li class="menu-item-type-custom menu-item-object-custom menu-item-has-children"><a href="#">ABOUT US</a>
                                    <ul class="sub-menu">
                                        <li class="menu-item-1738"><a href="{% url 'main:history' %}">HISTORY</a></li>
                                        <li class="menu-item-1745"><a href="{% url 'main:vision_mission' %}">VISION & MISSION</a></li>
                                        <li class="menu-item-1742"><a href="{% url 'main:team' %}">THE TEAM</a></li>
                                        <li class="menu-item-1746"><a href="{% url 'main:testimonials' %}">TESTIMONIALS</a></li>
                                    </ul>
                                </li>
                                <li class="menu-item-type-custom menu-item-object-custom menu-item-has-children"><a href="#">CREATING IMPACT</a>
                                    <ul class="sub-menu">
                                        <li class="menu-item-1738"><a href="{% url 'main:statistics' %}">STATISTICS</a></li>
                                        <li class="menu-item-1745"><a href="{% url 'main:approach' %}">OUR APPROACH</a></li>
                                        <li class="menu-item-1742"><a href="{% url 'main:stories' %}">STORIES OF HOPE</a></li>
                                        <li class="menu-item-1742"><a href="{% url 'main:projects' %}">OUR PROJECTS</a></li>
                                    </ul>
                                </li>
                                <li class="menu-item-type-custom menu-item-object-custom menu-item-has-children"><a href="">HOW YOU CAN HELP</a>
                                    <ul class="sub-menu">
                                        <li class="menu-item-1738"><a href="{% url 'main:donate' %}">DONATE NOW</a></li>
                                        <li class="menu-item-1745"><a href="{% url 'main:volunteer' %}">VOLUNTEER WITH US</a></li>
                                    </ul>
                                </li>
                                <li class="menu-item-type-custom menu-item-has-children"><a href="#">CONSULTATION</a>
                                    <ul class="sub-menu">
                                        <li class="menu-item-1791"><a href="{% url 'main:expert_panelist' %}">EXPERT PANELISTS</a></li>
                                        <li class="menu-item-1758"><a href="{% url 'main:get_expert' %}">GET IN TOUCH WITH AN EXPERT</a></li>
                                        <li class="menu-item-1790"><a href="{% url 'main:trainings' %}">TRAININGS</a></li>
                                        <li class="menu-item-1760"><a href="{% url 'main:resources' %}">RESOURCES</a></li>
                                    </ul>
                                </li>
                                <li class="menu-item-has-children"><a href="#">MARKET LINKAGE</a>
                                    <ul class="sub-menu">
                                        <li><a href="{% url 'main:get_connected_to_market' %}">GET CONNECTED TO THE MARKETS</a></li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'main:jobs' %}">CAREERS</a></li> 
                                <li><a href="{% url 'main:contact' %}">CONTACT US</a></li>
                            </ul>
                        </div>
                        <!-- #site-navigation -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

main/templates/includes/footer.html
{% load static %}
<footer id="site-footer" class="site-footer bg-second">
    <div class="main-footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 col-sm-6">
                    <div id="media_image-1" class="widget widget_media_image">
                        <a href="/"><img src="{% static 'images/logo.svg' %}" alt=""></a>
                    </div>
                    <div id="custom_html-1" class="widget_text widget widget_custom_html">
                        <div class="textwidget custom-html-widget">
                            <p>We are a Non Governmental Organization that supports small holder farmers in production techniques and connects them to markets to have better access of their products.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6">
                    <section id="custom_html-2" class="widget_text widget widget_custom_html padding-left">
                        <h4 class="widget-title">Useful Links</h4>
                        <div class="textwidget custom-html-widget">
                            <ul class="padd-left">
                                <li><a href="{% url 'main:consultation' %}">Farmers' Consultation</a></li>
                                <li><a href="{% url 'main:trainings' %}">Farmers' Training</a></li>
                                <li><a href="{% url 'main:get_connected_to_market' %}">Market Linkage</a></li>
                                <li><a href="{% url 'main:volunteer' %}">Volunteer With Us</a></li>
                                <li><a href="{% url 'main:donate' %}">Donate Now</a></li>
                            </ul>
                        </div>
                    </section>
                </div>     
                <div class="col-md-4 col-sm-6">
                    <section id="custom_html-3" class="widget_text widget widget_custom_html padding-left mb-4">
                        <h4 class="widget-title">We are on social media!!</h4>
                        <div class="textwidget custom-html-widget">
                            <a href="https://www.instagram.com/Agriwezeshatz/" target="_blank"><img src="{% static 'images/insta.png' %}" alt=""></a>
                        </div>
                        <div id="google_translate_element" class="footer-language-button shadow-lg rounded pb-2 bg-second"><span class="ml-4" style="font-size: 14px !important;">Change Language</span></div>
                    </section>
                    <div class="mt-5">
                        <button type="button" class="btn btn-success btn-lg mb-3" style="background-color:#ffffff !important;color: #336633;"><a href="{% url 'dashboard:home' %}" target="_blank">Admin Panel</a></button><br>
                        <button type="button" class="btn btn-success btn-lg" style="background-color:#ffffff !important;color: #336633;"><a href="https://agriwezesha.co.tz/webmail" target="_blank">Webmail Login</a></button>
                    </div>
                </div>       
            </div>
        </div>
    </div>
    <!-- .main-footer -->
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <div class="footer-copyright">
                        <span style="font-size:1.2rem;" translate="no"><span style="color:#fff;">&copy;&nbsp<script>document.write(new Date().getFullYear())</script>  Agriwezesha</span>-Developed By&nbsp;<a target="_blank" href="https://bafrocodes.co.tz"><span style="color:#fff;">Bafrocodes</span></a></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- .copyright-footer -->
    <a id="back-to-top" href="#" class="show"></a>
</footer>

main/templates/includes/mobile_header.html
{% load static %}
<div class="header_mobile">
    <div class="mlogo_wrapper clearfix">
        <div class="mobile-logo">
            <a href="/"><img src="{% static 'images/logo-white.svg' %}" alt="Logo"></a>
        </div>
        <div id="mmenu_toggle" class="mmenu_toggle">
            <button></button>
        </div>
    </div>
    <div class="mmenu_wrapper">
        <div class="mobile_nav collapse">
            <ul id="menu-main-menu" class="mobile_mainmenu">
                <li class=""><a href="/">Home</a>
                </li>
                <li class="menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-1731"><a href="#">ABOUT US</a>
                    <ul class="sub-menu">
                        <li class="menu-item-1738"><a href="{% url 'main:history' %}">HISTORY</a></li>
                        <li class="menu-item-1745"><a href="{% url 'main:vision_mission' %}">VISION & MISSION</a></li>
                        <li class="menu-item-1742"><a href="{% url 'main:team' %}">THE TEAM</a></li>
                        <li class="menu-item-1746"><a href="{% url 'main:testimonials' %}">TESTIMONIALS</a></li>
                    </ul>
                </li>
                <li class="menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-1789"><a href="#">CREATING IMPACT</a>
                    <ul class="sub-menu">
                        <li class="menu-item-1738"><a href="{% url 'main:statistics' %}">STATISTICS</a></li>
                        <li class="menu-item-1745"><a href="{% url 'main:approach' %}">OUR APPROACH</a></li>
                        <li class="menu-item-1742"><a href="{% url 'main:stories' %}">STORIES OF HOPE</a></li>
                            <li class="menu-item-1742"><a href="{% url 'main:stories' %}">STORIES OF HOPE</a></li>
                        <li class="menu-item-1742"><a href="{% url 'main:projects' %}">OUR PROJECTS</a></li>
                    </ul>
                </li>
                <li class="menu-item-has-children"><a href="#">HOW YOU CAN HELP</a>
                    <ul class="sub-menu">
                        <li class="menu-item-1738"><a href="{% url 'main:donate' %}">DONATE NOW</a></li>
                        <li class="menu-item-1745"><a href="{% url 'main:volunteer' %}">VOLUNTEER WITH US</a></li>
                    </ul>
                </li>
                <li class="menu-item-has-children"><a href="#">CONSULTATION</a>
                    <ul class="sub-menu">
                        <li class="menu-item-1791"><a href="{% url 'main:expert_panelist' %}">EXPERT PANELISTS</a></li>
                        <li class="menu-item-1758"><a href="{% url 'main:get_expert' %}">GET IN TOUCH WITH AN EXPERT</a></li>
                        <li class="menu-item-1790"><a href="{% url 'main:trainings' %}">TRAININGS</a></li>
                        <li class="menu-item-1760"><a href="{% url 'main:resources' %}">RESOURCES</a></li>
                    </ul>
                </li>
                <li class="menu-item-has-children"><a href="#">MARKET LINKAGE</a>
                    <ul class="sub-menu">
                        <li><a href="{% url 'main:get_connected_to_market' %}">GET CONNECTED TO THE MARKETS</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'main:jobs' %}">CAREERS</a></li> 
                <li><a href="{% url 'main:contact' %}">CONTACT US</a></li>
            </ul>
        </div>
    </div>
</div>

main/templates/includes/scripts.html
    {% load static %}
    <script type='text/javascript' src="{% static 'js/jquery.min.js' %}"></script>
	<script type='text/javascript' src="{% static 'js/countto.min.js' %}"></script>
	<script type='text/javascript' src="{% static 'js/jquery.isotope.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/slick.min.js' %}"></script>
	<script type='text/javascript' src="{% static 'js/royal_preloader.min.js' %}"></script>
	<script type='text/javascript' src="{% static 'js/scripts.js' %}"></script>
	<script type='text/javascript' src="{% static 'js/header-footer.js' %}"></script>

	<script type="text/javascript" src="{% static 'revolution/js/jquery.themepunch.tools.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
    <!-- RS5.0 Extensions Files -->
    <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.video.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.kenburn.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.migration.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'revolution/js/extensions/revolution.extension.parallax.min.js' %}"></script>

        <!-- Sweet Alerts -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>

main/templates/includes/top_bar.html
{% load static %}
        <!-- Top bar start / class css: topbar-dark -->
        <div id="header_topbar" class="header-topbar md-hidden sm-hidden clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <!-- contact info -->
                        <ul class="info-list fleft">
                            <li><i class="fa fa-map-marker color-light"></i> Sanga Sanga,Morogoro-Tanzania.</li>
                            <li><i class="fa fa-phone color-light"></i><a href="tel:+255783124619"> (+255)- 783124619</a></li>
                        </ul>
                        <!-- contact info close -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Top bar close -->