aconfig/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('JAYBLA-admin/', admin.site.urls),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
    path('users/',include('users.urls',namespace='users')),    
    path('',include('main.urls',namespace='main'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .views import *


app_name = 'dashboard'

urlpatterns = [    
    path('',dashboard, name='home'),

    #Jobs
    path('career/new/', create_job, name='create_job'),
    path('careers/', job_list, name='jobs'),
    path('careers/<int:job_id>/update/', update_job, name='update-job'),
    path('careers/<int:job_id>/', job_detail, name='job-detail'),
    path('careers/<int:job_id>/delete/', job_delete, name='delete-job'),

    #Projects
    path('projects/', projectlist,name='projectlist'),
    path('projects/new/', create_project, name='create_project'),
    path('projects/<int:project_id>/', project_detail, name='project-detail'),
    path('projects/<int:p_id>/update/', update_project, name='update-project'),
    path('projects/<int:p_id>/delete/', project_delete, name='delete-project'),

    #Project_Images
    path('project-images/', images,name='images'),
    path('project-images/new/', project_images, name='add_images'),    
    path('project-images/<int:image_id>/delete/', project_photo_delete, name='delete-project-image'),
    
        #Agroforests
    path('agroforests/', agroforestlist,name='agroforestlist'),
    path('agroforests/new/', create_agroforest, name='create_agroforest'),
    path('agroforests/<int:project_id>/', agroforest_detail, name='agroforest-detail'),
    path('agroforests/<int:p_id>/update/', update_agroforest, name='update-agroforest'),
    path('agroforests/<int:p_id>/delete/', agroforest_delete, name='delete-agroforest'),     
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home,name='site-home'),
    path('contact/', views.contact,name='contact'),
    path('ajax-contact/', views.process_contact, name='contact_post'),
    path('ajax-partiner/', views.process_partiner, name='partiner_post'),
    path('ajax-expert/', views.process_expert, name='expert_post'),
    path('ajax-market/', views.process_market, name='market_post'),
    path('ajax-donation/', views.process_donation, name='donation_post'),
    path('history/', views.history,name='history'),
    path('careers/', views.careers,name='careers'), 
    path('careers/announced-jobs', views.jobs,name='jobs'), 
    path('volunteer/', views.volunteer,name='volunteer'), 
    path('approach/', views.approach,name='approach'), 
    path('donate/', views.donate,name='donate'),
    path('expert-panelist/', views.expert_panelist,name='expert_panelist'),    
    path('get-connected-to-market/', views.get_connected_to_market,name='get_connected_to_market'),    
    path('get-expert/', views.get_expert,name='get_expert'),    
    path('resources/', views.resources,name='resources'),    
    path('statistics/', views.statistics,name='statistics'),        
    path('stories-of-hope/', views.stories,name='stories'),    
    path('team/', views.team,name='team'),
    path('testimonials/', views.testimonials,name='testimonials'),  
    path('trainings/', views.trainings,name='trainings'),  
    path('vision-mission/', views.vision_mission,name='vision_mission'),
    path('consultation/', views.consultation,name='consultation'),
    path('projects/', views.projects,name='projects'),    
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from users import views as user_views


app_name = 'users'

urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/authbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login -Admin Panel</title>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'auth/assets/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'auth/assets/vendors/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'auth/assets/css/app.css' %}">
    <link rel="stylesheet" href="{% static 'auth/assets/css/pages/auth.css' %}">
</head>

<body>
    <div id="auth">

        <div class="row h-100">
            <div class="col-lg-6 d-none d-lg-block">
                <div id="auth-right">
                </div>
            </div>
            <div class="col-lg-6 col-12">
                <div id="auth-left">
                    <div class="auth-logo d-flex justify-content-center">
                        <a href="#"><img src="{% static 'images/logo.svg' %}" alt="Logo" syle="width:300px !important; height:auto;"></a>
                    </div>                    
                    {% block content %}
                        
                    {% endblock content %} 
                </div>
            </div>

        </div>

    </div>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Agriwezesha-{% block title %}{{title}}{% endblock title %}</title>
    
	<link rel="stylesheet" id="bootstrap-css" href="{% static 'css/bootstrap.css' %}" type="text/css" media="all">
	<link rel="stylesheet" id="awesome-font-css" href="{% static 'css/font-awesome.css' %}" type="text/css" media="all">
	<link rel="stylesheet" id="ionicon-font-css" href="{% static 'css/ionicon.css' %}" type="text/css" media="all">
    <link rel="stylesheet" id="royal-preload-css" href="{% static 'css/royal-preload.css' %}" type="text/css" media="all">
	<link rel="stylesheet" id="slick-slider-css" href="{% static 'css/slick.css' %}" type="text/css" media="all">
	<link rel="stylesheet" id="slick-theme-css" href="{% static 'css/slick-theme.css' %}" type="text/css" media="all">
	<link rel="stylesheet" id="consultax-style-css" href="{% static 'style.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'custom.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'counter-section.css' %}" type="text/css" media="all">

    <!-- Owl Theme Default CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <!-- Owl Carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">


	<!-- RS5.0 Main Stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'revolution/css/settings.css' %}">

    <!-- RS5.0 Layers and Navigation Styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'revolution/css/layers.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'revolution/css/navigation.css' %}">

        <!-- Sweet alert -->
  <link href="{% static 'css/sweetalert2.css' %}" rel="stylesheet">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    <link rel="shortcut icon" href="{% static 'images/logo.svg' %}">
    <style>
   .goog-logo-link {
        display:none !important;
    } 
        
    .goog-te-gadget {
        color: transparent !important;
    } 

    .goog-te-banner-frame.skiptranslate {
    display: none !important;
    }

    .goog-te-gadget{
      margin-left: 20px;
    }
    .goog-te-combo{
      padding-left:30px;
      padding-right:30px;
      padding-top: 5px;
      padding-bottom: 5px;
      font-size:18px !important;      
    }

    </style>
    
    {% block stylesheet %}
        
    {% endblock stylesheet %}
        
</head>
<body class="royal_preloader">
	<div id="page" class="site">

    <header id="site-header" class="site-header header-transparent header-fixed sticky-header mobile-header-blue">
        <!-- Main header start - Header Home-1, Default -->
        {% include 'includes/top_bar.html' %}

        <!-- Main header start -->
        {% include 'includes/desktop_header.html' %}
        <!-- Main header close -->

        {% include 'includes/mobile_header.html' %}

    </header>
    <!-- #site-header -->

    <div id="content" class="site-content">
        
        {% block slider %}
            
        {% endblock slider %}
            
        
        {% block content %}
           
        {% endblock content %}
            

    </div>
    <!-- #content -->

    {% include 'includes/footer.html' %}
    <!-- #site-footer -->
</div>

	{% include 'includes/scripts.html' %}
	<script>
        jQuery(document).ready(function () {
            jQuery("#revolution-slider").revolution({
                sliderType: "standard",
                sliderLayout: 'fullscreen',
                delay: 7500,
                navigation: {
                    arrows: { enable: true }
                },
                spinner: "off",
                gridwidth: 1140,
                gridheight: 700,
                disableProgressBar: "on",
                responsiveLevels:[1920,1024,768,481],gridwidth:[1170,768,481,300],gridheight:[700,700,700,700]
            });
        });
    </script>

    
  
  <script type="text/javascript">
    function googleTranslateElementInit() {
      new google.translate.TranslateElement({pageLanguage: 'en',layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL }, 
   'google_translate_element');
    }
  </script>
  <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

    <script src="{% static 'js/sweetalert2.js' %}"></script>
    <!-- Owl Carousel JS -->
    <script src="{% static 'js/owl.carousel.js' %}"></script>

    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/counter-section.js' %}"></script>

    
    {% block javascript %}
        
    {% endblock javascript %}
        
</body>
</html>

templates/main_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />

    <title>Agriwezesha | Admin Panel</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'dashboard/main/plugins/fontawesome-free/css/all.min.css' %}" />
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static 'dashboard/main/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}" />
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dashboard/main/css/adminlte.min.css' %}" />
    <link rel="stylesheet" href="{% static 'dashboard/main/css/custom.css' %}" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet" />
    <script src="https://cdn.ckeditor.com/ckeditor5/35.2.1/classic/ckeditor.js"></script>
    <!-- Sweet alert -->
    <link href="{% static 'css/sweetalert2.css' %}" rel="stylesheet" />
  </head>
  <body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
    <div class="wrapper">
      <!-- Navbar -->
      <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'dashboard:home' %}" class="nav-link">Home</a>
          </li>
          <li class="nav-item d-none d-sm-inline-block float-right">
            <a href="{% url 'users:logout' %}" class="btn btn-outline-secondary nav-link">Logout</a>
          </li>
        </ul>
      </nav>
      <!-- /.navbar -->

      <!-- Main Sidebar Container -->
      <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{% url 'dashboard:home' %}" class="brand-link"><img src="{% static 'images/logo-white.svg' %}" alt="Logo" class="brand-image" /></a>

        <!-- Sidebar -->
        <div class="sidebar">
          <!-- Sidebar Menu -->
          <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
              <li class="nav-header">
                <span style="
                    font-family: 'Montserrat', sans-serif !important;
                    font-size: 24px !important;
                    color: white;
                    font-weight: 700;
                  ">CAREERS</span>
              </li>
              <li class="nav-item">
                <a href="{% url 'dashboard:create_job' %}" class="nav-link">
                  <i class="fas fa-plus-square"></i>
                  <p>New Job Advertisement</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'dashboard:jobs' %}" class="nav-link">
                  <i class="fas fa-list-alt"></i>
                  <p>Jobs Advertisement List</p>
                </a>
              </li>
              <li class="nav-header">
                <span style="
                    font-family: 'Montserrat', sans-serif !important;
                    font-size: 24px !important;
                    color: white;
                    font-weight: 700;
                  ">PROJECTS</span>
              </li>
              <li class="nav-item">
                <a href="{% url 'dashboard:create_project' %}" class="nav-link">
                  <i class="fas fa-plus-square"></i>
                  <p>Add Project</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'dashboard:projectlist' %}" class="nav-link">
                  <i class="fas fa-list-alt"></i>
                  <p>Projects List</p>
                </a>
              </li>
              <li class="nav-header">
                <span style="
                    font-family: 'Montserrat', sans-serif !important;
                    font-size: 24px !important;
                    color: white;
                    font-weight: 700;
                  ">
                  PROJECT <br />
                  PHOTOS
                </span>
              </li>
              <li class="nav-item">
                <a href="{% url 'dashboard:add_images' %}" class="nav-link">
                  <i class="fas fa-plus-square"></i>
                  <p>Add Project Photos</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'dashboard:images' %}" class="nav-link">
                  <i class="fas fa-list-alt"></i>
                  <p>All Photos</p>
                </a>
              </li>
              <li class="nav-header">
                <span style="
                    font-family: 'Montserrat', sans-serif !important;
                    font-size: 24px !important;
                    color: white;
                    font-weight: 700;
                  ">AGROFOREST</span>
              </li>
              <li class="nav-item">
                <a href="{% url 'dashboard:create_agroforest' %}" class="nav-link">
                  <i class="fas fa-plus-square"></i>
                  <p>Add Agroforest Project</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'dashboard:agroforestlist' %}" class="nav-link">
                  <i class="fas fa-list-alt"></i>
                  <p>All Agroforests</p>
                </a>
              </li>
            </ul>
          </nav>
          <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Main content -->
        <section class="content mb-150">
          {% block content %}

          {% endblock %}
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
      </aside>
      <!-- /.control-sidebar -->

      <!-- Main Footer -->
      <footer class="main-footer text-center">
        <strong>
          Copyright &copy;<script>
                            document.write(new Date().getFullYear())
                          </script>
          <a href="#">Agriwezesha</a>.
        </strong>
        All rights reserved.
      </footer>
    </div>
    <!-- ./wrapper -->

    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="{% static 'dashboard/main/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'dashboard/main/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{% static 'dashboard/main/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dashboard/main/js/adminlte.js' %}"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="{% static 'dashboard/main/js/demo.js' %}"></script>

    <!-- PAGE PLUGINS -->
    <!-- jQuery Mapael -->
    <script src="{% static 'dashboard/main/plugins/jquery-mousewheel/jquery.mousewheel.js' %}"></script>
    <script src="{% static 'dashboard/main/plugins/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'dashboard/main/plugins/jquery-mapael/jquery.mapael.min.js' %}"></script>
    <script src="{% static 'dashboard/main/plugins/jquery-mapael/maps/usa_states.min.js' %}"></script>
    <!-- ChartJS -->
    <script src="{% static 'dashboard/main/plugins/chart.js/Chart.min.js' %}"></script>

    <!-- PAGE SCRIPTS -->
    <script src="{% static 'dashboard/main/js/pages/dashboard2.js' %}"></script>
    <script>
      ClassicEditor.create(document.querySelector('#skillseditor'), {
        toolbar: ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote'],
        heading: {
          options: [
            {
              model: 'paragraph',
              title: 'Paragraph',
              class: 'ck-heading_paragraph'
            },
            {
              model: 'heading1',
              view: 'h1',
              title: 'Heading 1',
              class: 'ck-heading_heading1'
            },
            {
              model: 'heading2',
              view: 'h2',
              title: 'Heading 2',
              class: 'ck-heading_heading2'
            }
          ]
        }
      }).catch((error) => {
        console.log(error)
      })
    </script>
    <script>
      ClassicEditor.create(document.querySelector('#qualeditor'), {
        toolbar: ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote'],
        heading: {
          options: [
            {
              model: 'paragraph',
              title: 'Paragraph',
              class: 'ck-heading_paragraph'
            },
            {
              model: 'heading1',
              view: 'h1',
              title: 'Heading 1',
              class: 'ck-heading_heading1'
            },
            {
              model: 'heading2',
              view: 'h2',
              title: 'Heading 2',
              class: 'ck-heading_heading2'
            }
          ]
        }
      }).catch((error) => {
        console.log(error)
      })
    </script>
    <script>
      ClassicEditor.create(document.querySelector('#reseditor'), {
        toolbar: ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote'],
        heading: {
          options: [
            {
              model: 'paragraph',
              title: 'Paragraph',
              class: 'ck-heading_paragraph'
            },
            {
              model: 'heading1',
              view: 'h1',
              title: 'Heading 1',
              class: 'ck-heading_heading1'
            },
            {
              model: 'heading2',
              view: 'h2',
              title: 'Heading 2',
              class: 'ck-heading_heading2'
            }
          ]
        }
      }).catch((error) => {
        console.log(error)
      })
    </script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap4.min.js"></script>
    <script src="{% static 'js/sweetalert2.js' %}"></script>

    {% block javascript %}

    {% endblock %}
  </body>
</html>